#!/bin/bash

# Get draw helix and a sequence
curl -OL https://raw.githubusercontent.com/bioSyntax/bioSyntax/master/dev/scripts/drawHelix.sh
curl -OL https://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chrmt.fsa

# install gtop via npm in ~/.local/bin, first create a folder that is in the PATH
mkdir -p ~/.local/bin
npm install marked-terminal --prefix ~/.local/bin
npm install gtop --prefix ~/.local/bin

# to create alias for gtop ("~/.local/bin" is in the PATH)
cd ~/.local/bin
ln -s ~/.local/bin/node_modules/gtop/bin/gtop gtop
